### ISSUE TITLE
Update DMM Controller Address

### ISSUE THREAD

**Issue by coreycaplan3** [zeriontech/defi-sdk#114]
The DeFi Money Market Controller address is outdated now. 

The old address was `0x4CB120Dd1D33C9A3De8Bc15620C7Cd43418d77E2 `

The new one is `0xB07EB3426d742cda9120931e7028d54F9dF34A3e `

**Comment by cr-igor** [comment]
Hi, @coreycaplan3 ! 
We are not using the hardcoded controller address, we use one returned from `controller()` method of MTokens

**Comment by coreycaplan3** [comment]
Ah okay!  How are you discovering new tokens we add to the protocol then? Reason why I posted this is because we added mUSDT as an asset type

**Comment by coreycaplan3** [comment]
Bump @cr-igor

**Comment by coreycaplan3** [comment]
Bump again @cr-igor

**Comment by coreycaplan3** [comment]
Bump @cr-igor

**Comment by sobolev-igor** [comment]
Hi @coreycaplan3, I sooo sorry I haven't noticed your messages. I'm pretty sure we had mUSDT working all this time.
