### ISSUE TITLE
[Aave V2] aCRV is not shown in the balance

### ISSUE THREAD

**Issue by gasolin** [zeriontech/defi-sdk#142]
compare https://debank.com/ and https://app.zerion.io/ result, found `aCRV` is not shown in the `Aave V2` balance

**Comment by sobolev-igor** [comment]
Hi, I've added BAL, CRV and GUSD support to Aave, thanks for the issue!

**Comment by gasolin** [comment]
@sobolev-igor I'd like to learn a bit the insight of how defi-sdk works,
could you point out the commit or PR link that related to this fix?

**Comment by sobolev-igor** [comment]
I've just added new supported tokens to Aave adapters in [AdapterRegistry](https://etherscan.io/address/0x06fe76b2f432fdfecaef1a7d4f6c3d41b5861672#writeContract) contract, it means that it will iterate over these tokens (aBAL, aCRV, and aGUSD) too, when determining user's deposits/loans. btw, the txes are not mined, yet.

**Comment by gasolin** [comment]
thanks, is it goes through the `updateProtocolAdapter` method and fill the `newSupportedTokens` with `aBAL, aCRV, and aGUSD` contract address?
https://etherscan.io/address/0x06fe76b2f432fdfecaef1a7d4f6c3d41b5861672#writeContract

**Comment by sobolev-igor** [comment]
@gasolin yes, also I've updated debt adapters with BAL, CRV and GUSD addresses
