### ISSUE TITLE
Asset adapters are missing in Support Protocols

### ISSUE THREAD

**Issue by gasolin** [zeriontech/defi-sdk#148]
https://github.com/zeriontech/defi-sdk#supported-protocols

almost all Asset adapters links are missing, might due to architecture update #96

**Comment by sobolevigor986** [comment]
Hi, thanks for noticing! Readme was copied from `master` branch, so the links are broken now. The actual version of docs may be found [here](https://docs.zerion.io)! And if you switch to `master` branch the links will lead to actual implementations of adapters)

**Comment by gasolin** [comment]
good to know!

Is there an estimate time to merge to `interactive`, or mark the active branch as the default branch?

**Comment by sobolevigor986** [comment]
@gasolin unfortunately, it's deep in our backlog, if you want to see the current list of supported protocols, visit https://docs.zerion.io/supported-protocols
