### ISSUE TITLE
RealT read-only adapter

### ISSUE THREAD

**Issue by abalyasnikov** [zeriontech/defi-sdk#18]
Все что у меня есть:
- Сайт: https://realt.co/
- Список активных ассетов :
`
{"results":[{"name":"9943 MARLOWE ST.","address":"0xe5f7ef61443fc36ae040650aa585b0395aef77c8","totalTokens":1000,"price":63.75,"ownedTokens":"0","balance":0},{"name":"16200 FULLERTON","address":"0x22c8ecf727c23422f47093b562ec53c139805301","totalTokens":3800,"price":161.84,"ownedTokens":"0","balance":0},{"name":"18483 MANSFIELD","address":"0xb1d42642c6da784a5498180fdc64df8f8f2bb773","totalTokens":900,"price":68.52,"ownedTokens":"0","balance":0},{"name":"5942 AUDUBON RD","address":"0x43688910273f199b8ae2ca018c13918fb3d37b58","totalTokens":750,"price":77.73,"ownedTokens":"0","balance":0},{"name":"10024 APPOLINE ST","address":"0x5807ca447851c98569c567963b25b1c83d41bebc","totalTokens":4000,"price":145.56,"ownedTokens":"0","balance":0},{"name":"9336 PATTON ST","address":"0xed42cedcadbfbcaa3e6f411b09567c2c0b5ad28f","totalTokens":1000,"price":62.7,"ownedTokens":"0","balance":0},{"name":"20200 LESURE ST","address":"0x395c47a421c254ae42253764a7f56e0ee0cddac5","totalTokens":1000,"price":69.4,"ownedTokens":"0","balance":0}]}`

**Comment by sobolev-igor** [comment]
RealT tokens does not require read adapters
