### ISSUE TITLE
Aave result from adapter contract getBalances() does not contain LEND deposit

### ISSUE THREAD

**Issue by LefterisJP** [zeriontech/defi-sdk#60]
Hello guys!

In parallel with other querying methods we started utilizing your Adapter contracts to get some overview of DeFi balances in Rotki.
https://github.com/rotki/rotki/blob/19204d766a88407e35cd056a327fddaf625659ac/rotkehlchen/chain/ethereum/zerion.py

We noticed that if the balance of an address is queried that has `LEND` deposited in the Aave Lending Pool then this is not returned by the Adapter contract. So we had to make a "special case" fix for it: https://github.com/rotki/rotki/pull/1137. Essentially querying the lending pool directly for LEND balances for each address.

Are you aware of the problem? Any idea if a fix can be provided at some point so we can get rid of our ugly fix?

**Comment by sobolev-igor** [comment]
Hi, @LefterisJP!
Could you please provide an example address? I see aLEND token (0x7D2D3688Df45Ce7C552E19c27e007673da9204B8) in the list of supported tokens for the **AaveAssetAdapter**, so everything should be working fine.

**Comment by LefterisJP** [comment]
Gladly! We tried with this address: `0x21d05071cA08593e13cd3aFD0b4869537e015C92`

**Comment by sobolev-igor** [comment]
![image](https://user-images.githubusercontent.com/44194758/87252465-d10d5980-c48c-11ea-83ed-88bd05c5acf8.png)

I'm having this response on etherscan, it includes aLEND and LEND balances.

**Comment by LefterisJP** [comment]
@sobolev-igor Ah man ....I should have also checked Etherscan read contract before bothering you. I had tested our interface with the zerion adapter contracts with all of our accounts and they were correct.

But apparently LEND uncovered a bug. So the problem was on our side and we are fixing it here: https://github.com/rotki/rotki/pull/1150

Thanks a lot for the quick response over the weekend.

**Comment by sobolev-igor** [comment]
Not a problem!
Glad to help you 😊
